Gemfile
Gemfile.lock
app/models/activity.rb
config/environments/development.rb
config/storage.yml
db/migrate/20230829134950_create_active_storage_tables.active_storage.rb
db/schema.rb
db/seeds.rb

added images to seed, configured cloudinary
changed seed price from 14E to 14 for seeding purposes

adding seeding images

---

app/controllers/participations_controller.rb
config/routes.rb

hi guys, i have created the participations controller, i cant tested it yet. so hopefully we can test it together tomorrow.

participations controller is created and hasn't been tested yet

---

app/models/activity.rb
app/views/activities/index.html.erb
db/seeds.rb

added images.- multiple - this is reflected in the seeds. 
the index will be changed to show photo.first
activity model has_many_attached : photos 
bonne channce

adding multiple images to seed - changed index images to photo.first

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_topnavbar.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_show.scss
app/controllers/activities_controller.rb
app/javascript/controllers/map_controller.js
app/javascript/controllers/toggle_map_controller.js
app/views/activities/show.html.erb
app/views/chatrooms/show.html.erb
app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_topnavbar.html.erb

- Finished main features on the show page (picture, title, map, description, participate button)
- I have some features to add :
Calender
Buttons_paths on the index page

finished show page front-end

---

app/models/activity.rb
app/views/participations/my_dashboard.html.erb
config/routes.rb
db/seeds.rb

the controller has been tested

---

config/environments/production.rb

dns config

---

app/views/devise/registrations/new.html.erb
app/views/shared/_topnavbar.html.erb

Update signup form - now its working 
Sign out link_path fixed

signup-function

---

app/views/devise/registrations/edit.html.erb
app/views/shared/_topnavbar.html.erb

edit button is implemented, please take a look :))

edit button is implemented

---

app/assets/stylesheets/components/_topnavbar.scss
app/assets/stylesheets/pages/_home.scss
app/controllers/activities_controller.rb
app/controllers/reviews_controller.rb
app/javascript/controllers/map_controller.js
app/javascript/controllers/toggle_map_controller.js
app/models/activity.rb
app/models/review.rb
app/models/user.rb
app/views/activities/show.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_topnavbar.html.erb
db/migrate/20230904122546_add_content_to_reviews.rb
db/migrate/20230904151605_add_user_to_reviews.rb
db/schema.rb
db/seeds.rb

- Average of reviews done
- For the activity which has between 4 and 5 stars --> Best activity ever with an award
- Button connect on the index page disapears when the user signed in

Reviews and button

---

app/assets/stylesheets/pages/_chatroom.scss
app/views/chatrooms/show.html.erb

just adding some css to chatrooms

adding css to chatroom

---

app/controllers/application_controller.rb
app/views/devise/registrations/edit.html.erb

implemented the edit button and avatar
hopefully it works

implemented the edit button and avatar

---

config/cable.yml

added some config to cable yml

heroku config

---

app/assets/stylesheets/pages/_chatroom.scss
app/assets/stylesheets/pages/_edit.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/news.scss
app/views/chatrooms/show.html.erb
app/views/devise/registrations/edit.html.erb

front-end edit form

---

app/assets/stylesheets/pages/_chatroom.scss
app/views/chatrooms/show.html.erb
app/views/devise/registrations/edit.html.erb

fixing last problems

---

Gemfile.lock
app/views/shared/_navbar.html.erb
app/views/shared/_topnavbar.html.erb

hided the news buttons (2)

---

app/assets/stylesheets/pages/news.scss
app/views/news/index.html.erb
db/migrate/20230907074826_add_theme_to_news.rb
db/migrate/20230907075949_add_link_to_news.rb
db/schema.rb
db/seeds.rb

adding news seed images

---

db/seeds.rb

seeds is filled, hopefully nothing is error

seeds is filled perfectly

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_topnavbar.scss
app/assets/stylesheets/pages/_chatroom.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_login.scss
app/assets/stylesheets/pages/_my_dashboard.scss
app/assets/stylesheets/pages/_show.scss
app/views/activities/index.html.erb
app/views/activities/show.html.erb
app/views/devise/sessions/new.html.erb
app/views/news/index.html.erb
app/views/participations/my_dashboard.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_topnavbar.html.erb
config/initializers/geocoder.rb
db/seeds.rb

finished adaptation of the screen

---

app/assets/stylesheets/pages/_news.scss
app/views/news/index.html.erb

News frontend

---

app/assets/stylesheets/pages/_news.scss
db/seeds.rb

seeds now work
